import Link from 'next/link'
import { Header } from '../../components/Header'
import { Footer } from '../../components/Footer'
import { searchPublicIntelligence } from '../../lib/data/search'
export const metadata={title:'Search | KAPORAL INTELLIGENCE',description:'Search published KAPORAL research, verified data series and public intelligence sections.'}
export default async function SearchPage({searchParams}:{searchParams:Promise<{q?:string}>}){
 const{q=''}=await searchParams;const results=q?await searchPublicIntelligence(q):[]
 const groups=[['research','Research'],['data','Data series'],['desk','Intelligence desks'],['page','Methodology & policy']] as const
 return <main className="searchPage"><Header/><section className="searchHero"><div className="shell"><span className="eyebrow">SEARCH KAPORAL</span><h1>Search public intelligence.</h1><p>Published investigations, verified data series, desks and public methodology. Private newsroom material is never searchable here.</p><form className="searchForm" action="/search"><input name="q" defaultValue={q} placeholder="Search Bitcoin, inflation, Cameroon, options…" aria-label="Search query"/><button className="goldButton" type="submit">Search</button></form></div></section><section className="shell searchResults"><h2>{q?`Results for “${q}”`:'Enter a topic, market or data series'}</h2>{q&&results.length===0?<div className="searchEmpty">No public KAPORAL material matches this query yet. Unpublished research and private Studio data are excluded by design.</div>:groups.map(([kind,label])=>{const items=results.filter(r=>r.kind===kind);return items.length?<section className="searchGroup" key={kind}><div className="searchGroupHead"><span className="eyebrow">{label}</span><strong>{items.length} result{items.length===1?'':'s'}</strong></div><div className="researchCardGrid">{items.map(r=><Link className="researchCard" href={r.href} key={r.key}><small>{r.meta??label}</small><h3>{r.title}</h3><p>{r.summary??'Open public KAPORAL intelligence.'}</p><span>Open →</span></Link>)}</div></section>:null})}</section><Footer/></main>
}
