import {EventKind, EconomicEvent} from './calendar'

export type Scenario = {key: string; title: string; observation: string; mechanism: string; options: string[]; invalidation: string; sources: {label: string; url: string}[]}
const sourceMap: Record<EventKind, {label: string; url: string}[]> = {
  cpi: [{label:'BLS CPI release schedule',url:'https://www.bls.gov/schedule/news_release/cpi.htm'}, {label:'Federal Reserve research on macro surprises',url:'https://www.federalreserve.gov/econres/feds/how-markets-process-macro-news-the-importance-of-investor-attention.htm'}],
  pce: [{label:'BEA PCE data',url:'https://www.bea.gov/data/personal-consumption-expenditures-price-index'}, {label:'Federal Reserve research on macro surprises',url:'https://www.federalreserve.gov/econres/feds/how-markets-process-macro-news-the-importance-of-investor-attention.htm'}],
  fomc: [{label:'Federal Reserve FOMC calendar',url:'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm'}, {label:'Federal Reserve monetary policy',url:'https://www.federalreserve.gov/monetarypolicy.htm'}],
  payrolls: [{label:'BLS Employment Situation',url:'https://www.bls.gov/news.release/empsit.toc.htm'}],
  ppi: [{label:'BLS PPI release schedule',url:'https://www.bls.gov/schedule/news_release/ppi.htm'}],
  gdp: [{label:'BEA GDP',url:'https://www.bea.gov/data/gdp/gross-domestic-product'}],
}

export function scenariosForEvent(event: EconomicEvent): Scenario[] {
  const sources = sourceMap[event.kind]
  if (event.kind === 'fomc') return [
    {key:'above_consensus',title:'More restrictive than expected',observation:'A higher path for rates or a more restrictive communication can tighten financial conditions.',mechanism:'Rates, the dollar and real yields may reprice together; risk assets can be more sensitive to the size and speed of the surprise than to the meeting label.',options:['Wait for the statement and press conference to be read together.','Stage exposure only if the price response confirms the thesis.','Keep a written invalidation level and position-size limit.'],invalidation:'The statement, projections and market reaction point in different directions or liquidity is too thin.',sources},
    {key:'in_line',title:'Close to the expected path',observation:'An in-line decision can reduce one source of uncertainty, but it does not guarantee a directional move.',mechanism:'Markets may focus on guidance, growth language, balance-sheet policy or the next data release.',options:['Hold existing risk within the user’s plan.','Compare the decision with the prior path before changing exposure.','Avoid treating a calm first reaction as confirmation.'],invalidation:'The press conference materially changes the expected path.',sources},
    {key:'below_consensus',title:'More accommodative than expected',observation:'A lower path or easier communication can loosen conditions, but growth concerns can offset the initial response.',mechanism:'The same announcement can support risk assets through lower rates or hurt them if it signals deteriorating growth.',options:['Wait for rates, dollar and risk assets to confirm the same mechanism.','Use a staged decision instead of an all-at-once trade.','Record what would make the thesis wrong.'],invalidation:'The move is driven by a growth scare or reverses after the full communication.',sources},
  ]
  const label = event.kind === 'cpi' ? 'CPI' : event.kind === 'pce' ? 'PCE inflation' : event.kind.toUpperCase()
  return [
    {key:'above_consensus',title:`${label} above expectations`,observation:`An upside inflation surprise can increase the chance that rates stay restrictive, but the effect depends on the size, composition and market regime.`,mechanism:`Real yields and the dollar may rise. Gold and crypto can weaken in that transmission path, but neither response is a rule; positioning, growth and liquidity can dominate.`,options:['Wait for the release and initial rate/dollar reaction rather than guessing the number.','Stage or reduce new risk if the user’s plan requires lower volatility.','Compare headline, core and relevant revisions where available.'],invalidation:'Rates and the dollar do not confirm the mechanism, or later data changes the policy path.',sources},
    {key:'in_line',title:`${label} near expectations`,observation:'A result near expectations may leave the market focused on details, revisions and the next policy communication.',mechanism:'The first price move can fade when the surprise is small or already priced in.',options:['Keep the existing plan and avoid forcing a trade.','Watch the next confirmed catalyst.','Use a smaller test only when the user has a defined risk limit.'],invalidation:'A meaningful component or revision changes the policy interpretation.',sources},
    {key:'below_consensus',title:`${label} below expectations`,observation:`A downside inflation surprise can support a softer-rate narrative, but weaker growth can complicate the response.`,mechanism:'Lower yields may support gold and risk assets; a growth shock or liquidity stress can reverse that relationship.',options:['Confirm the move across rates, dollar and the target asset.','Prefer staged exposure and document the alternative explanation.','Do not treat an educational scenario as a buy or sell instruction.'],invalidation:'The move is reversed, or growth/liquidity evidence contradicts the soft-rate mechanism.',sources},
  ]
}
