import Link from 'next/link'
import { getStudioOverview } from '../../lib/data/content'
import { KScoreForm, StoryIntakeForm } from '../../components/StoryIntakeForm'

export default async function StudioPage(){
  const data = await getStudioOverview()
  if(!data.authorized){return <main className="studio-shell"><section className="studio-lock"><p className="eyebrow">KAPORAL RESEARCH OS</p><h1>Private newsroom workspace</h1><p>Authentication is active. This workspace is visible only to approved researchers, editors and administrators.</p><div className="lockActions"><Link href="/auth">Sign in</Link><Link href="/">Return to public intelligence</Link></div></section></main>}
  const canEdit=['editor','admin'].includes(data.profile.role)
  const completedRuns=data.runs.filter((r:any)=>r.status==='completed').length
  return <main className="studio-shell"><section className="studio-head"><div><p className="eyebrow">KAPORAL RESEARCH OS · v0.5</p><h1>Newsroom Command Center</h1><p>{data.profile.display_name ?? 'Researcher'} · {data.profile.role}</p></div><div className="workspaceActions"><Link href="/research">Public research</Link><Link href="/">Public site ↗</Link></div></section>
    <section className="studio-kpis"><div><small>STORY QUEUE</small><b>{data.stories.length}</b></div><div><small>EDITORIAL PIPELINE</small><b>{data.articles.length}</b></div><div><small>REVIEW TASKS</small><b>{data.reviews.length}</b></div><div><small>COMPLETED AGENT RUNS</small><b>{completedRuns}</b></div></section>
    <section className="studio-grid">
      <article className="studio-panel"><h2>Signal & story queue</h2>{data.stories.length?data.stories.map((s:any)=><Link className="studio-row studioLink" href={`/studio/story/${s.id}`} key={s.id}><div><strong>{s.title}</strong><small>{s.detected_by} · {s.story_type} · {s.primary_region??'Global'}</small></div><span>{s.status}</span></Link>):<p>No story candidates yet. The hourly Signal Scout and human intake feed this queue.</p>}</article>
      <article className="studio-panel"><h2>Editorial pipeline</h2>{data.articles.length?data.articles.map((a:any)=><Link className="studio-row studioLink" href={`/studio/article/${a.id}`} key={a.id}><strong>{a.headline}</strong><span>{a.status}</span></Link>):<p>No linked article drafts yet. Open a story workspace to create one after evidence collection.</p>}</article>
      <article className="studio-panel"><h2>Review gates</h2>{data.reviews.length?data.reviews.map((r:any)=><div className="studio-row" key={r.id}><strong>{r.reviewer_role.replaceAll('_',' ')}</strong><span>{r.decision ?? 'pending'}</span></div>):<p>No review tasks yet. Publication requires contrarian, quant, standards and Editor-in-Chief PASS decisions.</p>}</article>
      <article className="studio-panel"><h2>Agent audit trail</h2>{data.runs.length?data.runs.slice(0,12).map((r:any)=><div className="studio-row" key={r.id}><div><strong>{r.agent_name.replaceAll('_',' ')}</strong><small>{r.model??'no model'} · {r.run_type}</small></div><span>{r.status}</span></div>):<p>No model runs yet. Open a story workspace to run evidence-grounded analysts.</p>}</article>
    </section>
    <section className="studio-panel studioAgentPolicy"><p className="eyebrow">OPERATING RULE</p><h2>Agents can investigate. Only humans can publish.</h2><p>The Signal Scout can create candidates automatically. Analyst agents can summarize, challenge, quantify and propose claims. The final transition to <code>published</code> is protected by an editor-only server endpoint and a PostgreSQL trigger that independently checks evidence, claims and four mandatory reviews.</p><div className="agent-pills"><span>Signal Scout</span><span>Niche Scout</span><span>Source Analyst</span><span>Macro</span><span>Crypto</span><span>Options</span><span>Africa</span><span>Business</span><span>Technology</span><span>Contrarian</span><span>Quant</span><span>Standards</span><span>Visual Intelligence</span></div></section>
    <section className="studio-tools"><StoryIntakeForm/><KScoreForm stories={data.stories.map((s:any)=>({id:s.id,title:s.title}))}/>{canEdit&&<div className="studioForm"><div className="formTitle"><span>03</span><h3>Editorial drafting</h3></div><p>Drafts are now created from inside a story workspace so every article stays linked to its source pack, claims, K-SCORE and agent audit trail.</p><Link className="goldButton" href={data.stories[0]?`/studio/story/${data.stories[0].id}`:'/studio'}>Open research queue</Link></div>}</section>
  </main>
}
