import { test, expect } from '@playwright/test'

test('Africa annual history opens with data and retains honest short-range and source labels', async ({ page, request, isMobile }, info) => {
  const annualResponse = await request.get('/api/intelligence/series/CMR_GDP_GROWTH')
  expect(annualResponse.status()).toBe(200)
  const annual = await annualResponse.json()
  expect(annual.range).toBe('MAX')
  expect(annual.frequency).toBe('annual')
  expect(annual.history.length).toBeGreaterThan(1)
  expect(annual.history.every((point: {observedAt:string}) => Date.parse(point.observedAt) <= Date.parse(annual.asOf))).toBe(true)
  expect((await request.get('/api/intelligence/series/CMR_GDP_GROWTH?range=invalid')).status()).toBe(400)
  await page.goto('/africa')
  const cameroon = page.locator('.africaCountryCard').filter({ has: page.locator('.countryCardHead strong', { hasText: 'Cameroon' }) })
  await expect(cameroon).toContainText('Reporting year')
  await expect(cameroon).toContainText('local currency units per US$1')
  await expect(cameroon.getByRole('link', { name: 'Cameroon — GDP Growth source', exact: true })).toHaveAttribute('href', 'https://api.worldbank.org/v2/country/CMR/indicator/NY.GDP.MKTP.KD.ZG')
  await cameroon.locator('a[href="/data/cmr_gdp_growth"]').click()
  await expect(page).toHaveURL(/\/data\/cmr_gdp_growth$/)
  await expect(page.getByRole('button', { name: 'MAX', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.historyChart')).toBeVisible()
  await expect(page.locator('.deskHero')).toContainText('Reporting year')
  await expect(page.locator('.historyChartBlock')).toContainText('not a release date or a live quote')
  const slider = page.getByRole('slider', { name: 'Inspect Cameroon — GDP Growth observation', exact: true })
  await slider.focus(); await slider.press('Home')
  await expect(slider).toHaveValue('0')
  await expect(page.locator('.chartReadout')).toContainText('Reporting year')
  await expect(page.locator('.chartReadout')).not.toContainText('00:00 UTC')
  await page.getByRole('button', { name: '30D', exact: true }).click()
  await expect(page.getByRole('button', { name: '30D', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'MAX', exact: true }).click()
  await expect(page.locator('.historyChart')).toBeVisible()
  await page.locator('.historyTable summary').click()
  await expect(page.getByRole('columnheader', { name: 'Reporting year', exact: true })).toBeVisible()
  if (isMobile) await page.setViewportSize({ width: 844, height: 390 })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  await info.attach('africa-annual-chart', { body: await page.locator('.historyChartBlock').screenshot({ scale: 'css' }), contentType: 'image/png' })
})

test('version-specific Signal Lab stays private and uncached when signed out', async ({ page }) => {
  const response = await page.goto('/studio/signals?model=00000000-0000-4000-8000-000000000001')
  expect(response?.status()).toBe(200)
  expect(response?.headers()['cache-control']).toContain('no-store')
  await expect(page.getByRole('heading', { name: 'Private quantitative research workspace' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Sign in', exact: true })).toHaveAttribute('href', '/auth')
  await expect(page.getByRole('heading', { name: 'Complete version-specific forward report' })).toHaveCount(0)
  await expect(page.getByLabel('Model version', { exact: true })).toHaveCount(0)
  await expect(page.locator('meta[name="robots"]')).toHaveAttribute('content', /noindex/)
})

test('event search opens an official FOMC decision with scenarios and a real chart', async ({ page }, info) => {
  await page.goto('/events')
  await page.getByRole('searchbox', { name: 'Find a market event' }).fill('FOMC')
  await page.getByLabel('Release type').selectOption('fomc')
  const cards = page.locator('.eventGrid .eventCard')
  await expect(cards.first()).toBeVisible()
  for (const card of await cards.all()) await expect(card).toContainText('FOMC')
  await cards.first().click()
  await expect(page.locator('.eventTiming')).toContainText('Final meeting day')
  await expect(page.locator('.eventTiming a')).toHaveAttribute('href', 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm')
  await expect(page.locator('.scenarioGrid')).toContainText('More restrictive than expected')
  await expect(page.locator('.decisionTable')).toContainText('Stay uninvested')
  await expect(page.locator('.historyChart')).toBeVisible()
  await expect(page.locator('.chartReadout')).toContainText('USD')
  await expect(page.getByRole('link', { name: 'Gold futures chart →' })).toHaveAttribute('href', '/data/gold')
  await page.getByRole('button', { name: 'Save to watchlist', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Sign in to save', exact: true })).toHaveAttribute('href', '/auth')
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  await info.attach('event-scenarios-and-chart', { body: await page.screenshot({ fullPage: true, scale: 'css' }), contentType: 'image/png' })
})

test('Bitcoin chart changes range, supports keyboard inspection, saves only after sign-in and survives landscape', async ({ page, isMobile }, info) => {
  await page.goto('/data/btc')
  await page.getByRole('button', { name: '30D', exact: true }).click()
  await expect(page.getByRole('button', { name: '30D', exact: true })).toHaveAttribute('aria-pressed', 'true')
  const slider = page.getByRole('slider', { name: 'Inspect BTC price observation' })
  await slider.focus(); await slider.press('Home')
  await expect(slider).toHaveValue('0')
  await expect(page.locator('.chartReadout')).toContainText('USD')
  await page.getByRole('button', { name: 'Save to watchlist', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Sign in to save', exact: true })).toHaveAttribute('href', '/auth')
  await page.locator('.historyTable summary').click()
  await expect(page.locator('.historyTable tbody tr').first()).toBeVisible()
  if (isMobile) await page.setViewportSize({ width: 844, height: 390 })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
  await info.attach('bitcoin-chart-interaction', { body: await page.locator('.historyChartBlock').screenshot({ scale: 'css' }), contentType: 'image/png' })
})

test('private workspace endpoints reject unsigned mutations', async ({ request }) => {
  for (const path of ['/api/account/preferences','/api/studio/events/sync','/api/studio/models/run','/api/studio/newsletter/issue','/api/studio/newsletter/queue','/api/studio/newsletter/deliver']) {
    const response = await request.post(path, { data: { status: 'published', confirmDelivery: true } })
    expect(response.status(), path).toBe(401)
    expect(response.headers()['cache-control'], path).toContain('no-store')
  }
})

test('public newsletter archive is indexable while consent pages remain private', async ({ page }) => {
  await page.goto('/newsletter')
  // Omitting robots metadata permits indexing. Reading an absent optional tag
  // must not consume the test timeout before the consent-page assertion runs.
  const robots = await page.locator('meta[name="robots"]').evaluateAll(nodes => nodes.map(node => node.getAttribute('content') ?? ''))
  expect(robots.join(' ')).not.toContain('noindex')
  await page.goto('/newsletter/confirm')
  await expect(page.locator('meta[name="robots"]')).toHaveAttribute('content', /noindex/)
})
