'use client'
import { FormEvent, useMemo, useState } from 'react'

function bodyToText(body:any){const blocks=Array.isArray(body?.blocks)?body.blocks:[];return blocks.map((b:any)=>b?.text??'').filter(Boolean).join('\n\n')}
const mandatory=['contrarian','quant','standards','editor_in_chief']

type Props={article:any;reviews:any[];role:string;sources:any[];claims:any[];predictions:any[]}

export function ArticleReviewClient({article,reviews,role,sources,claims,predictions}:Props){
 const [message,setMessage]=useState(''); const [busy,setBusy]=useState('')
 const [headline,setHeadline]=useState(article.headline??''); const [dek,setDek]=useState(article.dek??''); const [bodyText,setBodyText]=useState(bodyToText(article.body)); const [confidence,setConfidence]=useState(article.confidence??'medium'); const [readerLevel,setReaderLevel]=useState(article.reader_level??'research')
 const canEdit=['editor','admin'].includes(role)
 const latestPass=useMemo(()=>new Map(mandatory.map(r=>[r,reviews.some(x=>String(x.reviewer_role).replaceAll('-','_')===r&&x.decision==='pass')])),[reviews])
 const readiness={body:bodyText.trim().length>0,dek:dek.trim().length>=20,sources:sources.length>0,claims:claims.length>0&&claims.every(c=>['supported','not_applicable'].includes(c.verification_status)),reviews:mandatory.every(r=>latestPass.get(r))}
 async function save(e:FormEvent){e.preventDefault();setBusy('save');setMessage('');const res=await fetch('/api/studio/article/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({articleId:article.id,headline,dek,bodyText,confidence,readerLevel})});const data=await res.json();setMessage(res.ok?'Draft saved and moved to review.':data.error||'Save failed.');setBusy('')}
 async function review(roleName:string,decision:string){const notes=window.prompt(`${roleName.replaceAll('_',' ')} notes`,decision==='pass'?'Review passed.':'Describe the required revision.')??'';setBusy(roleName);setMessage('');const res=await fetch('/api/studio/article/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({articleId:article.id,reviewerRole:roleName,decision,notes})});const data=await res.json();setMessage(res.ok?`${roleName.replaceAll('_',' ')} recorded: ${decision}.`:data.error||'Review failed.');setBusy('');if(res.ok)setTimeout(()=>location.reload(),350)}
 async function publish(){if(!window.confirm('Publish this investigation to the public site? The database will reject publication if any mandatory gate is incomplete.'))return;setBusy('publish');setMessage('');const res=await fetch('/api/studio/article/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({articleId:article.id})});const data=await res.json();setMessage(res.ok?`Published successfully: /article/${data.article.slug}`:data.error||'Publication gate rejected this article.');setBusy('');if(res.ok)setTimeout(()=>location.reload(),450)}
 return <>
  <form className="researchCard articleEditor" onSubmit={save}><div className="researchCardTitle"><span>01</span><h2>Article Editor</h2><b>{article.status}</b></div><label>Headline<input value={headline} onChange={e=>setHeadline(e.target.value)} required/></label><label>Dek / reader promise<textarea rows={3} value={dek} onChange={e=>setDek(e.target.value)} placeholder="Explain what the reader will understand and why it matters."/></label><div className="formSplit"><label>Reader level<select value={readerLevel} onChange={e=>setReaderLevel(e.target.value)}><option value="discover">Discover</option><option value="follow">Follow</option><option value="research">Research</option></select></label><label>Confidence<select value={confidence} onChange={e=>setConfidence(e.target.value)}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label></div><label>Research body<textarea rows={18} value={bodyText} onChange={e=>setBodyText(e.target.value)} placeholder="Write evidence-led paragraphs here. Structured visual blocks are added separately in later iterations."/></label><button className="goldButton" disabled={!canEdit||!!busy}>{busy==='save'?'Saving…':'Save for review'}</button></form>
  <section className="researchCard"><div className="researchCardTitle"><span>02</span><h2>Publication Readiness</h2><b>{Object.values(readiness).filter(Boolean).length}/5</b></div><div className="readinessGrid"><div className={readiness.body?'ready':'notReady'}><b>Body</b><span>{readiness.body?'Ready':'Missing'}</span></div><div className={readiness.dek?'ready':'notReady'}><b>Dek</b><span>{readiness.dek?'Ready':'Needs ≥20 chars'}</span></div><div className={readiness.sources?'ready':'notReady'}><b>Sources</b><span>{sources.length}</span></div><div className={readiness.claims?'ready':'notReady'}><b>Claims</b><span>{claims.length?`${claims.filter(c=>['supported','not_applicable'].includes(c.verification_status)).length}/${claims.length} verified`:'Missing'}</span></div><div className={readiness.reviews?'ready':'notReady'}><b>Reviews</b><span>{mandatory.filter(r=>latestPass.get(r)).length}/4 pass</span></div></div><p className="tinyDisclaimer">These UI checks are informative. The definitive publication gate runs inside PostgreSQL when status changes to published.</p></section>
  <section className="researchCard"><div className="researchCardTitle"><span>03</span><h2>Mandatory Reviews</h2><b>4</b></div><div className="reviewGateGrid">{mandatory.map(r=><article key={r}><div><b>{r.replaceAll('_',' ')}</b><span className={latestPass.get(r)?'pass':'pending'}>{latestPass.get(r)?'PASS':'PENDING'}</span></div><div><button disabled={!canEdit||!!busy} onClick={()=>review(r,'pass')}>Pass</button><button disabled={!canEdit||!!busy} onClick={()=>review(r,'revise')}>Revise</button><button disabled={!canEdit||!!busy} onClick={()=>review(r,'hold')}>Hold</button></div></article>)}</div><div className="reviewHistory">{reviews.slice(0,12).map(r=><p key={r.id}><b>{r.reviewer_role}</b> · {r.decision??'pending'} {r.notes?`— ${r.notes}`:''}</p>)}</div></section>
  <section className="researchCard publishGate"><div className="researchCardTitle"><span>04</span><h2>Human Publication Gate</h2><b>{article.status}</b></div><p>AI agents do not have a publish action. An authenticated editor triggers this endpoint, and the database independently rechecks evidence and all four passed reviews.</p><button className="goldButton" disabled={!canEdit||!!busy||article.status==='published'} onClick={publish}>{article.status==='published'?'Published':busy==='publish'?'Checking gates…':'Human Approve & Publish'}</button>{message&&<p className="researchMessage">{message}</p>}</section>
 </>
}
