'use client'
import {useEffect,useState} from 'react'
type Preferences={timezone:string;newsletter_frequency:string;event_alerts:boolean;preferred_assets:string[]}
export function PreferencePanel(){
  const [preferences,setPreferences]=useState<Preferences>({timezone:'UTC',newsletter_frequency:'weekly',event_alerts:true,preferred_assets:['BTC','ETH','GOLD']})
  const [symbol,setSymbol]=useState(''); const [status,setStatus]=useState(''); const [busy,setBusy]=useState(false)
  useEffect(()=>{fetch('/api/account/preferences',{cache:'no-store'}).then(async r=>{const body=await r.json();if(r.ok&&body.preferences)setPreferences(body.preferences);if(!r.ok)setStatus(body.error||'Workspace unavailable')}).catch(()=>setStatus('Workspace unavailable'))},[])
  async function save(){setBusy(true);setStatus('');const r=await fetch('/api/account/preferences',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({timezone:preferences.timezone,newsletterFrequency:preferences.newsletter_frequency,eventAlerts:preferences.event_alerts,preferredAssets:preferences.preferred_assets})});const body=await r.json();setStatus(r.ok?'Saved.':body.error||'Could not save.');setBusy(false)}
  async function add(){const value=symbol.trim().toUpperCase();if(!value)return;setBusy(true);const r=await fetch('/api/account/preferences',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({symbol:value})});setStatus(r.ok?`${value} added to your watchlist.`:'Could not add watchlist item.');setSymbol('');setBusy(false)}
  return <div className="preferencePanel"><div><span className="eyebrow">PRIVATE WORKSPACE</span><h2>Alerts & watchlist</h2><p>Choose how KAPORAL should organize event briefings. Saving a symbol tracks interest; it does not create an investment instruction.</p></div><div className="preferenceGrid"><label>Newsletter cadence<select value={preferences.newsletter_frequency} onChange={e=>setPreferences({...preferences,newsletter_frequency:e.target.value})}><option value="weekly">Weekly</option><option value="weekday">Weekdays</option><option value="material_event">Material events</option><option value="off">Off</option></select></label><label>Timezone<input value={preferences.timezone} onChange={e=>setPreferences({...preferences,timezone:e.target.value})} placeholder="Europe/Amsterdam"/></label><label className="checkRow"><input type="checkbox" checked={preferences.event_alerts} onChange={e=>setPreferences({...preferences,event_alerts:e.target.checked})}/> Event reminders</label><button className="goldButton" type="button" onClick={save} disabled={busy}>{busy?'Saving…':'Save preferences'}</button></div><div className="watchlistAdd"><label>Add an asset symbol<input value={symbol} onChange={e=>setSymbol(e.target.value)} placeholder="BTC, ETH, GOLD" maxLength={20}/></label><button className="outlineButton" type="button" onClick={add} disabled={busy}>Add to watchlist</button></div>{status&&<small className="preferenceStatus" role="status">{status}</small>}</div>
}
