'use client'
import { FormEvent, useState } from 'react'
import { createClient } from '../lib/supabase/client'

const agents=[
 ['niche_scout','Niche Scout'],['source_analyst','Source Analyst'],['macro_analyst','Macro Analyst'],['crypto_analyst','Crypto Analyst'],['options_analyst','Options Analyst'],['africa_analyst','Africa Analyst'],['business_analyst','Business Analyst'],['technology_analyst','Technology Analyst'],['contrarian_reviewer','Contrarian Reviewer'],['quant_reviewer','Quant Reviewer'],['standards_reviewer','Standards Reviewer'],['visual_intelligence_editor','Visual Intelligence Editor']
]

type Props={storyId:string;role:string;sources:any[];claims:any[];runs:any[];articles:any[]}

export function ResearchWorkspaceClient({storyId,role,sources,claims,runs,articles}:Props){
 const [message,setMessage]=useState(''); const [busy,setBusy]=useState('')
 const canEdit=['editor','admin'].includes(role)
 async function addSource(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy('source');setMessage('');const fd=new FormData(e.currentTarget);const url=String(fd.get('url')||'').trim();const supabase=createClient();const {data:auth}=await supabase.auth.getUser();const payload={url,title:String(fd.get('title')||'').trim()||null,publisher:String(fd.get('publisher')||'').trim()||null,source_type:String(fd.get('source_type')||'secondary'),reliability_score:Number(fd.get('reliability')||70),metadata:{added_via:'research_os'}};const {data:source,error:sErr}=await supabase.from('sources').upsert(payload,{onConflict:'url'}).select('id').single();if(sErr||!source){setMessage(sErr?.message||'Source could not be saved.');setBusy('');return}const {error}=await supabase.from('story_sources').upsert({story_candidate_id:storyId,source_id:source.id,note:String(fd.get('note')||'').trim()||null,added_by:auth.user?.id??null},{onConflict:'story_candidate_id,source_id'});setMessage(error?error.message:'Source added to the evidence pack.');setBusy('');if(!error)setTimeout(()=>location.reload(),350)}
 async function addClaim(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy('claim');setMessage('');const fd=new FormData(e.currentTarget);const supabase=createClient();const {data:auth}=await supabase.auth.getUser();const {error}=await supabase.from('story_claims').insert({story_candidate_id:storyId,claim_text:String(fd.get('claim_text')||'').trim(),claim_type:String(fd.get('claim_type')||'factual'),confidence:String(fd.get('confidence')||'medium'),verification_status:String(fd.get('verification_status')||'unverified'),evidence_note:String(fd.get('evidence_note')||'').trim()||null,created_by:auth.user?.id??null});setMessage(error?error.message:'Claim added to the verification ledger.');setBusy('');if(!error)setTimeout(()=>location.reload(),350)}
 async function runAgent(agent:string){setBusy(agent);setMessage('');try{const res=await fetch('/api/studio/agent/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({storyId,agent})});const data=await res.json();setMessage(res.ok?`${agent.replaceAll('_',' ')} completed. Review the structured output below.`:(data.error||'Agent run failed.'));if(res.ok)setTimeout(()=>location.reload(),500)}catch{setMessage('Agent request failed.')}finally{setBusy('')}}
 async function createDraft(){setBusy('draft');setMessage('');const res=await fetch('/api/studio/story/create-draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({storyId})});const data=await res.json();setMessage(res.ok?'Draft created and linked to this investigation.':data.error||'Draft creation failed.');setBusy('');if(res.ok)setTimeout(()=>location.reload(),450)}
 return <>
  <section className="researchOsGrid">
   <form className="researchCard" onSubmit={addSource}><div className="researchCardTitle"><span>01</span><h2>Source Pack</h2><b>{sources.length}</b></div><p>Attach the evidence before asking an agent to reason over it.</p><label>URL<input required name="url" type="url" placeholder="https://…"/></label><div className="formSplit"><label>Title<input name="title"/></label><label>Publisher<input name="publisher"/></label></div><div className="formSplit"><label>Evidence type<select name="source_type" defaultValue="secondary"><option value="primary">Primary</option><option value="secondary">Secondary</option><option value="market_data">Market data</option><option value="field_intelligence">Field intelligence</option><option value="expert_interview">Expert interview</option><option value="internal_analysis">Internal analysis</option></select></label><label>Reliability<input name="reliability" type="number" min="0" max="100" defaultValue="70"/></label></div><label>Research note<textarea name="note" rows={3} placeholder="Why this source matters, limitations, and what claim it supports."/></label><button className="goldButton" disabled={!!busy}>{busy==='source'?'Saving…':'Add source'}</button><div className="evidenceStack">{sources.slice(0,8).map((l:any)=><a key={l.source_id} href={l.source?.url} target="_blank" rel="noreferrer"><b>{l.source?.publisher??'Source'}</b><span>{l.source?.title??l.source?.url}</span><small>{l.source?.source_type} · reliability {l.source?.reliability_score??'—'}</small></a>)}</div></form>
   <form className="researchCard" onSubmit={addClaim}><div className="researchCardTitle"><span>02</span><h2>Claim Ledger</h2><b>{claims.length}</b></div><p>Every meaningful statement should have a type, confidence and verification state.</p><label>Claim<textarea required name="claim_text" rows={3}/></label><div className="formSplit"><label>Type<select name="claim_type"><option value="factual">Factual</option><option value="inference">Inference</option><option value="scenario">Scenario</option><option value="forecast">Forecast</option><option value="question">Question</option></select></label><label>Confidence<select name="confidence"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label></div><label>Verification<select name="verification_status"><option value="unverified">Unverified</option><option value="supported">Supported</option><option value="contested">Contested</option><option value="rejected">Rejected</option><option value="not_applicable">Not applicable</option></select></label><label>Evidence note<textarea name="evidence_note" rows={2}/></label><button className="goldButton" disabled={!!busy}>{busy==='claim'?'Saving…':'Add claim'}</button><div className="claimStack">{claims.slice(0,10).map((c:any)=><div key={c.id}><span>{c.verification_status}</span><b>{c.claim_type}</b><p>{c.claim_text}</p></div>)}</div></form>
  </section>
  <section className="researchCard agentRoom"><div className="researchCardTitle"><span>03</span><h2>Agent Room</h2><b>{runs.length}</b></div><p>Agents reason only over the supplied evidence pack and verified live metrics. They cannot publish.</p><div className="agentRunGrid">{agents.map(([id,label])=><button key={id} disabled={!!busy} onClick={()=>runAgent(id)}>{busy===id?'Running…':label}</button>)}</div>{message&&<p className="researchMessage">{message}</p>}<div className="agentRunList">{runs.slice(0,12).map((r:any)=><article key={r.id}><div><strong>{r.agent_name.replaceAll('_',' ')}</strong><span>{r.status} · {r.model??'no model'}</span></div><p>{r.output_summary||r.error||'Run recorded; open structured output in the database audit trail.'}</p><small>{new Date(r.started_at).toLocaleString()}</small></article>)}</div></section>
  <section className="researchCard draftGate"><div className="researchCardTitle"><span>04</span><h2>Editorial Handoff</h2><b>{articles.length}</b></div><p>A story becomes an article only when an editor chooses to create a draft. Publication still requires the database evidence/review gate.</p>{articles.length?<div className="articleLinks">{articles.map((a:any)=><a key={a.id} href={`/studio/article/${a.id}`}><b>{a.headline}</b><span>{a.status} · {a.reader_level}</span></a>)}</div>:canEdit?<button className="goldButton" disabled={!!busy} onClick={createDraft}>{busy==='draft'?'Creating…':'Create linked draft'}</button>:<p>Research role can prepare evidence; an editor creates the publication draft.</p>}</section>
 </>
}
