'use client'
import { FormEvent, useMemo, useState } from 'react'
import { createClient } from '../lib/supabase/client'

const storyTypes=['breaking','explainer','deep_dive','opportunity','risk','structural_trend','investigation','data_story','africa_lens','scenario_watch']
export function StoryIntakeForm(){
 const [status,setStatus]=useState(''); const [busy,setBusy]=useState(false)
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setStatus('');const fd=new FormData(e.currentTarget);const payload={title:String(fd.get('title')||'').trim(),thesis_seed:String(fd.get('thesis')||'').trim(),story_type:String(fd.get('story_type')||'investigation'),primary_region:String(fd.get('region')||'Global').trim(),primary_sector:String(fd.get('sector')||'Cross-asset').trim(),detected_by:'human_editor',status:'idea'};const supabase=createClient();const {error}=await supabase.from('story_candidates').insert(payload);if(error)setStatus(error.message);else{setStatus('Story candidate added to the research queue.');e.currentTarget.reset();setTimeout(()=>location.reload(),450)}setBusy(false)}
 return <form className="studioForm" onSubmit={submit}><div className="formTitle"><span>01</span><h3>Story intake</h3></div><label>Working title<input name="title" required placeholder="What changed — and why might it matter?"/></label><label>Thesis seed<textarea name="thesis" rows={3} placeholder="Initial mechanism, tension or question. Not a conclusion."/></label><div className="formSplit"><label>Story type<select name="story_type">{storyTypes.map(t=><option key={t} value={t}>{t.replaceAll('_',' ')}</option>)}</select></label><label>Region<input name="region" defaultValue="Global"/></label></div><label>Primary sector<input name="sector" defaultValue="Cross-asset"/></label><button className="goldButton" disabled={busy}>{busy?'Adding…':'Add to signal queue'}</button>{status&&<small className="formStatus">{status}</small>}</form>
}

type Story={id:string;title:string}
const dimensions=[
 ['economic_impact','Economic impact',20],['market_impact','Market impact',15],['novelty','Novelty',10],['search_demand','Search demand',10],['strategic_importance','Strategic importance',15],['audience_breadth','Audience breadth',10],['long_term_relevance','Long-term relevance',10],['visualization_potential','Visualization potential',5],['original_analysis_potential','Original analysis potential',5]
] as const
export function KScoreForm({stories}:{stories:Story[]}){
 const [values,setValues]=useState<Record<string,number>>(Object.fromEntries(dimensions.map(([k])=>[k,50])));const [status,setStatus]=useState('');const [busy,setBusy]=useState(false)
 const total=useMemo(()=>dimensions.reduce((acc,[k,,w])=>acc+(values[k]||0)*w/100,0),[values])
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!stories.length)return;setBusy(true);setStatus('');const fd=new FormData(e.currentTarget);const payload:any={story_candidate_id:String(fd.get('story_id')),total_score:Number(total.toFixed(2)),rationale:String(fd.get('rationale')||'')};dimensions.forEach(([k])=>payload[k]=values[k]);const {error}=await createClient().from('k_scores').insert(payload);setStatus(error?error.message:`K-SCORE ${total.toFixed(1)} saved.`);setBusy(false)}
 return <form className="studioForm" onSubmit={submit}><div className="formTitle"><span>02</span><h3>K-SCORE gate</h3><b>{total.toFixed(0)}</b></div><label>Story<select name="story_id" required disabled={!stories.length}>{stories.length?stories.map(s=><option value={s.id} key={s.id}>{s.title}</option>):<option>No candidates yet</option>}</select></label><div className="scoreGrid">{dimensions.map(([k,label,w])=><label key={k}><span>{label}<em>{w}%</em></span><input type="range" min="0" max="100" value={values[k]} onChange={e=>setValues(v=>({...v,[k]:Number(e.target.value)}))}/><b>{values[k]}</b></label>)}</div><label>Rationale<textarea name="rationale" rows={3} placeholder="Why this story deserves — or does not deserve — newsroom resources."/></label><button className="goldButton" disabled={busy||!stories.length}>{busy?'Saving…':'Save K-SCORE'}</button>{status&&<small className="formStatus">{status}</small>}</form>
}

function slugify(s:string){return s.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,90)}
export function ArticleDraftForm(){
 const [status,setStatus]=useState('');const [busy,setBusy]=useState(false)
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setStatus('');const fd=new FormData(e.currentTarget);const headline=String(fd.get('headline')||'').trim();const bodyText=String(fd.get('body')||'').trim();const payload={headline,slug:slugify(headline),dek:String(fd.get('dek')||'').trim(),reader_level:String(fd.get('reader_level')||'follow'),status:'idea',body:{version:1,blocks:bodyText?[{type:'paragraph',text:bodyText}]:[]}};const {error}=await createClient().from('articles').insert(payload);if(error)setStatus(error.message);else{setStatus('Draft created.');e.currentTarget.reset();setTimeout(()=>location.reload(),450)}setBusy(false)}
 return <form className="studioForm" onSubmit={submit}><div className="formTitle"><span>03</span><h3>Article draft</h3></div><label>Headline<input name="headline" required placeholder="Answer-first, not clickbait"/></label><label>Dek<textarea name="dek" rows={2} placeholder="What the reader will understand after reading."/></label><label>Research depth<select name="reader_level"><option value="discover">Discover</option><option value="follow">Follow</option><option value="research">Research</option></select></label><label>Opening research note<textarea name="body" rows={5} placeholder="Initial editor note; structured blocks and evidence cards follow in the full editor."/></label><button className="goldButton" disabled={busy}>{busy?'Creating…':'Create draft'}</button>{status&&<small className="formStatus">{status}</small>}</form>
}
