import { Header } from '../../components/Header'
import { Footer } from '../../components/Footer'
import { createClient } from '../../lib/supabase/server'

function pct(v:any){return v==null?'—':`${Math.round(Number(v))}%`}
function date(v:any){return v?new Date(v).toLocaleDateString('en-GB',{year:'numeric',month:'short',day:'numeric'}):'—'}

export default async function TrackRecordPage(){
 const supabase=await createClient()
 const {data:predictions}=await supabase.from('predictions').select('id,statement,probability,target_metric,target_condition,horizon_start,horizon_end,invalidation_condition,status,published_at,article:articles(slug,headline,published_at),resolutions:prediction_resolutions(resolved_at,outcome,score,evidence)').order('published_at',{ascending:false}).limit(250)
 const rows=predictions??[]
 const resolved=rows.filter((p:any)=>Array.isArray(p.resolutions)&&p.resolutions.length)
 const scoreValues=resolved.flatMap((p:any)=>p.resolutions.map((r:any)=>r.score).filter((x:any)=>x!=null).map(Number))
 const avg=scoreValues.length?scoreValues.reduce((a:number,b:number)=>a+b,0)/scoreValues.length:null
 return <main><Header/><section className="productHero"><div className="shell"><p className="eyebrow">PREDICTION LEDGER</p><h1>We keep the receipts.</h1><p>Meaningful forward-looking statements are time-stamped, assigned a probability and horizon, given an invalidation condition, and resolved later against evidence.</p><div className="ledgerKpis"><div><small>RECORDED</small><b>{rows.length}</b></div><div><small>RESOLVED</small><b>{resolved.length}</b></div><div><small>OPEN</small><b>{rows.filter((p:any)=>p.status==='open').length}</b></div><div><small>AVG SCORE</small><b>{avg==null?'—':avg.toFixed(2)}</b></div></div></div></section><section className="shell productSection"><div className="sectionTitle"><div><span className="eyebrow">PUBLIC TRACK RECORD</span><h2>Forecasts are conditional, not promises.</h2></div><p>Empty is acceptable. A prediction appears here only after it is explicitly recorded in the research workflow.</p></div>{rows.length?<div className="ledgerTable">{rows.map((p:any)=><article key={p.id} className="ledgerRow"><div className="ledgerProbability"><b>{pct(p.probability)}</b><span>{p.status}</span></div><div className="ledgerStatement"><h3>{p.statement}</h3><p>{p.target_metric?`${p.target_metric}${p.target_condition?` · ${p.target_condition}`:''}`:'Target metric documented in the source investigation.'}</p>{p.invalidation_condition&&<small><strong>Invalidation:</strong> {p.invalidation_condition}</small>}</div><div className="ledgerHorizon"><small>HORIZON</small><b>{date(p.horizon_start)}</b><span>→ {date(p.horizon_end)}</span></div><div className="ledgerSource">{p.article?.slug?<a href={`/article/${p.article.slug}`}>{p.article.headline}</a>:<span>Standalone ledger entry</span>}<small>Logged {date(p.published_at)}</small></div>{p.resolutions?.length?<div className="ledgerResolution">{p.resolutions.map((r:any,i:number)=><div key={i}><b>{r.outcome}</b><span>{r.score==null?'unscored':`score ${Number(r.score).toFixed(2)}`}</span><small>{date(r.resolved_at)}</small></div>)}</div>:<div className="ledgerResolution pending">Unresolved</div>}</article>)}</div>:<div className="emptyResearch"><h3>No public predictions yet.</h3><p>KAPORAL will not backfill a fictional track record. Entries begin when reviewed investigations make explicit, scoreable forward statements.</p></div>}</section><Footer/></main>
}
