import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.3";
const H={"Content-Type":"application/json","Cache-Control":"no-store"};
type Series={id:string;code:string;provider_series_code:string|null;country_code:string|null;source_url:string|null;provider_id:string|null};
type Provider={id:string;slug:string};
type Pt={series_id:string;observed_at:string;value:number;raw_value:string;provider:string;metadata:Record<string,unknown>};
function keys(name:string){try{return JSON.parse(Deno.env.get(name)??"{}")}catch{return{}}}
function auth(req:Request){const k=req.headers.get("apikey");return !!k&&[...Object.values(keys("SUPABASE_PUBLISHABLE_KEYS")),...Object.values(keys("SUPABASE_SECRET_KEYS"))].includes(k)}
function num(v:unknown){if(v==null)return null;const s=String(v).trim().replace(/,/g,"");if(!s||s==="."||s==="null")return null;const n=Number(s);return Number.isFinite(n)?n:null}
async function fetchText(url:string){const c=new AbortController(),t=setTimeout(()=>c.abort(),18000);try{const r=await fetch(url,{headers:{"user-agent":"KaporalIntelligence/0.8 (+https://www.kaporalintelligence.com)"},signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
async function fetchJson(url:string){const c=new AbortController(),t=setTimeout(()=>c.abort(),20000);try{const r=await fetch(url,{headers:{accept:"application/json","user-agent":"KaporalIntelligence/0.8 (+https://www.kaporalintelligence.com)"},signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
async function fred(series:Series[]){const start=new Date(Date.now()-5*365.25*864e5).toISOString().slice(0,10),out:Pt[]=[];for(const s of series){if(!s.provider_series_code)continue;try{const csv=await fetchText(`https://fred.stlouisfed.org/graph/fredgraph.csv?id=${encodeURIComponent(s.provider_series_code)}&cosd=${start}`);const rows=csv.trim().split(/\r?\n/).slice(1).slice(-700);for(const row of rows){const [date,raw]=row.split(","),v=num(raw);if(!date||v===null)continue;out.push({series_id:s.id,observed_at:`${date.trim()}T00:00:00Z`,value:v,raw_value:String(raw).trim(),provider:"FRED",metadata:{series:s.provider_series_code,source_url:s.source_url,history_backfill:true}})}}catch(e){console.error("fred",s.code,e)}}return out}
async function worldBank(series:Series[]){const out:Pt[]=[];const groups=new Map<string,Series[]>();for(const s of series)if(s.country_code)groups.set(s.country_code,[...(groups.get(s.country_code)??[]),s]);const end=new Date().getUTCFullYear(),start=end-12;for(const [country,group] of groups){const indicators=[...new Set(group.map(s=>s.provider_series_code).filter(Boolean))].join(";");try{const p=await fetchJson(`https://api.worldbank.org/v2/country/${country}/indicator/${indicators}?source=2&format=json&date=${start}:${end}&per_page=1000`);const rows=Array.isArray(p)&&Array.isArray(p[1])?p[1]:[];for(const s of group){for(const r of rows){if(r?.indicator?.id!==s.provider_series_code||r?.value==null)continue;const v=num(r.value),year=String(r.date??"").slice(0,4);if(v===null||!/^\d{4}$/.test(year))continue;out.push({series_id:s.id,observed_at:`${year}-01-01T00:00:00Z`,value:v,raw_value:String(r.value),provider:"World Bank",metadata:{country_code:country,indicator_code:s.provider_series_code,year,source_url:s.source_url,history_backfill:true}})}}}catch(e){console.error("world-bank",country,e)}}return out}
async function yahoo(series:Series[]){const out:Pt[]=[];for(const s of series){if(!s.provider_series_code)continue;try{const p=await fetchJson(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(s.provider_series_code)}?interval=1d&range=2y`),r=p?.chart?.result?.[0],ts=Array.isArray(r?.timestamp)?r.timestamp:[],close=r?.indicators?.quote?.[0]?.close??[];for(let i=0;i<ts.length;i++){const v=num(close[i]);if(v===null)continue;out.push({series_id:s.id,observed_at:new Date(Number(ts[i])*1000).toISOString(),value:v,raw_value:String(close[i]),provider:"Yahoo Finance",metadata:{symbol:s.provider_series_code,source_url:s.source_url,history_backfill:true,secondary_provider:true}})}}catch(e){console.error("yahoo",s.code,e)}}return out}
async function upsertChunks(a:any,rows:Pt[]){let written=0;for(let i=0;i<rows.length;i+=500){const chunk=rows.slice(i,i+500);const {error}=await a.from("data_points").upsert(chunk,{onConflict:"series_id,observed_at",ignoreDuplicates:false});if(error)throw Error(error.message);written+=chunk.length}return written}
Deno.serve(async(req:Request)=>{if(req.method!=="POST")return new Response(JSON.stringify({error:"POST required"}),{status:405,headers:H});if(!auth(req))return new Response(JSON.stringify({error:"Unauthorized"}),{status:401,headers:H});const url=Deno.env.get("SUPABASE_URL")!,secret=keys("SUPABASE_SECRET_KEYS").default??Deno.env.get("SUPABASE_SECRET_KEY")??Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!secret)return new Response(JSON.stringify({error:"Service credential unavailable"}),{status:500,headers:H});const a=createClient(url,secret,{auth:{persistSession:false}});const {data:last}=await a.from("ingestion_runs").select("completed_at").eq("job_type","history_backfill").eq("status","success").order("completed_at",{ascending:false}).limit(1).maybeSingle();const force=(await req.json().catch(()=>({})))?.force===true;if(!force&&last?.completed_at&&Date.now()-Date.parse(last.completed_at)<20*3600e3)return new Response(JSON.stringify({ok:true,throttled:true,lastCompletedAt:last.completed_at}),{headers:H});const started_at=new Date().toISOString(),{data:run}=await a.from("ingestion_runs").insert({job_type:"history_backfill",status:"running",started_at}).select("id").single();try{const [{data:providers},{data:series}]=await Promise.all([a.from("data_providers").select("id,slug").eq("enabled",true),a.from("data_series").select("id,code,provider_id,provider_series_code,country_code,source_url").eq("is_public",true)]);const pm=new Map((providers as Provider[]??[]).map(p=>[p.id,p.slug])),by=(slug:string)=>(series as Series[]??[]).filter(s=>s.provider_id&&pm.get(s.provider_id)===slug);const [f,w,y]=await Promise.all([fred(by("fred")),worldBank(by("world-bank")),yahoo(by("yahoo-public"))]);const rows=[...f,...w,...y],written=await upsertChunks(a,rows),completed_at=new Date().toISOString();if(run?.id)await a.from("ingestion_runs").update({status:"success",rows_written:written,message:JSON.stringify({fred:f.length,world_bank:w.length,yahoo:y.length}),completed_at}).eq("id",run.id);return new Response(JSON.stringify({ok:true,rows:written,providers:{fred:f.length,worldBank:w.length,yahoo:y.length},completedAt:completed_at}),{headers:H})}catch(e){const message=e instanceof Error?e.message:String(e),completed_at=new Date().toISOString();if(run?.id)await a.from("ingestion_runs").update({status:"failed",message,completed_at}).eq("id",run.id);return new Response(JSON.stringify({ok:false,error:message}),{status:502,headers:H})}});