import Link from 'next/link'
import { Header } from '../Header'
import { Footer } from '../Footer'
import { getResearchIndex } from '../../lib/data/intelligence'

export async function ResearchIndex(){
  const {articles,predictions,weekly}=await getResearchIndex()
  return <main className="intelligencePage"><Header/><section className="deskHero"><div className="shell deskHeroGrid"><div><span className="eyebrow">KAPORAL RESEARCH</span><h1>Evidence first. Predictions scored later.</h1><p>The public research layer contains only human-approved investigations, published forecast entries and transparent weekly reviews.</p></div><aside><small>PUBLICATION RULE</small><strong>No agent can publish autonomously.</strong><span>Research runs can draft, challenge and model. Human approval is required for publication.</span></aside></div></section><section className="shell liveSection"><div className="liveSectionHead"><div><span className="eyebrow">INVESTIGATIONS</span><h2>Published research</h2></div><Link href="/methodology">Methodology →</Link></div>{articles.length?<div className="researchCardGrid">{articles.map(a=><Link href={`/article/${a.slug}`} className="researchCard" key={a.id}><small>{a.confidence??a.readerLevel}</small><h3>{a.headline}</h3><p>{a.dek}</p></Link>)}</div>:<div className="emptyResearch"><strong>The research engine is active; the public shelf is intentionally empty.</strong><p>The first flagship will appear only after source verification, domain analysis, contrarian review, quant review, standards review and human approval.</p></div>}</section><section className="deskCoverage"><div className="shell researchSplit"><div><span className="eyebrow">PREDICTION LEDGER</span><h2>Forward-looking claims must become auditable.</h2>{predictions.length?predictions.map((p:any)=><article className="ledgerRow" key={p.id}><b>{p.probability==null?'—':`${Math.round(Number(p.probability))}%`}</b><div><strong>{p.statement}</strong><p>{p.invalidation_condition?`Invalidated if: ${p.invalidation_condition}`:'Invalidation condition not published.'}</p></div><span>{p.status}</span></article>):<p className="emptyCopy">No public prediction entries yet. We will not backfill a track record retroactively.</p>}</div><div><span className="eyebrow">WEEKLY SELF-REVIEW</span><h2>What were we wrong about?</h2>{weekly.length?weekly.map((w:any)=><article className="weeklyRow" key={w.id}><b>Week of {w.week_start}</b><p>{w.what_failed||w.what_we_missed||'Published weekly review.'}</p></article>):<p className="emptyCopy">The public weekly scorecard begins after the first publication cycle.</p>}</div></div></section><section className="shell researchOSCallout"><span className="eyebrow">RESEARCH OS</span><h2>The private newsroom is already separate from the public site.</h2><p>Authorized researchers and editors use the protected Studio for story intake, K-SCORE, evidence, review and publishing workflow.</p><Link className="goldButton" href="/studio">Open Studio</Link></section><Footer/></main>
}
