import {NextResponse} from 'next/server'
import {createClient} from '../../../../../lib/supabase/server'
import {getUpcomingEvents} from '../../../../../lib/events/calendar-data'
export const dynamic='force-dynamic'; export const revalidate=0
async function staff(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return {supabase,user:null,role:null};const {data:profile}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle();return {supabase,user,role:profile?.role??null}}
export async function GET(){const {supabase,user,role}=await staff();if(!user||!['researcher','editor','admin'].includes(role??''))return NextResponse.json({error:'Research staff access required'},{status:403,headers:{'cache-control':'no-store'}});const {data,error}=await supabase.from('newsletter_issues').select('id,issue_key,title,dek,issue_date,status,reviewed_at,approved_at,published_at,created_at').order('issue_date',{ascending:false}).limit(30);if(error)return NextResponse.json({error:'Newsletter issue table is not available yet.'},{status:503,headers:{'cache-control':'no-store'}});return NextResponse.json({issues:data??[]},{headers:{'cache-control':'no-store'}})}
export async function POST(){const {supabase,user,role}=await staff();if(!user||!['researcher','editor','admin'].includes(role??''))return NextResponse.json({error:'Research staff access required'},{status:403,headers:{'cache-control':'no-store'}});const calendar=await getUpcomingEvents(8);const date=new Date().toISOString().slice(0,10);const issueKey=`market-letter-${date}`;const body={blocks:[{type:'heading',text:'Upcoming events to watch'},{type:'paragraph',text:'This draft uses official release calendars. Prior, consensus, actual and revision fields remain blank until separately sourced and reviewed.'},{type:'bullet_list',items:calendar.events.map(event=>`${event.kind.toUpperCase()}: ${event.title} — ${event.scheduledAt} (${event.precision} precision)` )},{type:'heading',text:'Decision guardrail'},{type:'paragraph',text:'Evaluate wait, stage, hold or reduce-risk options against the user’s own plan. This edition is educational and is not a personal recommendation.'}]};const result=await supabase.from('newsletter_issues').upsert({issue_key:titleCase(issueKey),title:`KAPORAL Market Letter — ${date}`,dek:'A source-labelled event brief prepared for human review.',body,issue_date:date,status:'draft',source_snapshot:{checkedAt:calendar.checkedAt,sourceState:calendar.sourceState,events:calendar.events},created_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'issue_key'}).select('id,issue_key,status').single();if(result.error)return NextResponse.json({error:'Could not create newsletter draft.'},{status:503,headers:{'cache-control':'no-store'}});return NextResponse.json({ok:true,issue:result.data},{headers:{'cache-control':'no-store'}})}
export async function PATCH(request:Request){const {supabase,user,role}=await staff();if(!user||!['researcher','editor','admin'].includes(role??''))return NextResponse.json({error:'Research staff access required'},{status:403,headers:{'cache-control':'no-store'}});const body=await request.json().catch(()=>null) as {id?:string;status?:string}|null;const next=body?.status;const allowed=['draft','review','approved','published','archived'];if(!body?.id||!allowed.includes(String(next)))return NextResponse.json({error:'Issue id and valid status required.'},{status:400,headers:{'cache-control':'no-store'}});if(['approved','published'].includes(String(next))&&!['editor','admin'].includes(role??''))return NextResponse.json({error:'Only an editor or administrator can approve or publish an issue.'},{status:403,headers:{'cache-control':'no-store'}});const patch:any={status:next,updated_at:new Date().toISOString()};if(next==='approved')Object.assign(patch,{reviewed_at:new Date().toISOString(),reviewed_by:user.id,approved_at:new Date().toISOString(),approved_by:user.id});if(next==='published')Object.assign(patch,{published_at:new Date().toISOString()});const result=await supabase.from('newsletter_issues').update(patch).eq('id',body.id).select('id,status,published_at').single();if(result.error)return NextResponse.json({error:'Newsletter status transition rejected.'},{status:503,headers:{'cache-control':'no-store'}});return NextResponse.json({ok:true,issue:result.data},{headers:{'cache-control':'no-store'}})}
function titleCase(value:string){return value}
