create table if not exists public.etf_fund_snapshots (
  id bigint generated by default as identity primary key,
  ticker text not null,
  issuer text not null,
  as_of date not null,
  nav_usd numeric,
  shares_outstanding numeric,
  aum_usd numeric,
  flow_usd numeric,
  flow_for_date date,
  source_url text not null,
  source_date_text text,
  source_method text not null default 'issuer_public_page',
  parser_version text not null default 'v1',
  metadata jsonb not null default '{}'::jsonb,
  ingested_at timestamptz not null default now(),
  constraint etf_fund_snapshots_ticker_asof_key unique (ticker, as_of),
  constraint etf_fund_snapshots_nav_check check (nav_usd is null or nav_usd > 0),
  constraint etf_fund_snapshots_shares_check check (shares_outstanding is null or shares_outstanding > 0),
  constraint etf_fund_snapshots_aum_check check (aum_usd is null or aum_usd > 0)
);

create index if not exists etf_fund_snapshots_ticker_asof_idx on public.etf_fund_snapshots(ticker, as_of desc);
create index if not exists etf_fund_snapshots_flow_date_idx on public.etf_fund_snapshots(flow_for_date desc) where flow_for_date is not null;

alter table public.etf_fund_snapshots enable row level security;
drop policy if exists "Public read ETF fund snapshots" on public.etf_fund_snapshots;
create policy "Public read ETF fund snapshots" on public.etf_fund_snapshots for select using (true);
grant select on public.etf_fund_snapshots to anon, authenticated;
revoke insert, update, delete on public.etf_fund_snapshots from anon, authenticated;

insert into public.data_providers(slug,name,provider_type,base_url,enabled,config)
values (
  'kaporal-etf-primary',
  'KAPORAL Derived ETF Flow',
  'derived_data',
  'https://www.kaporalintelligence.com/methodology',
  true,
  jsonb_build_object(
    'cost','free',
    'method','daily issuer shares outstanding change multiplied by prior business-day NAV',
    'publication_label','KAPORAL Estimated',
    'primary_sources',jsonb_build_array('BlackRock','Fidelity','Bitwise','21Shares','Franklin Templeton','VanEck','WisdomTree','Grayscale')
  )
)
on conflict (slug) do update set
  name=excluded.name,
  provider_type=excluded.provider_type,
  base_url=excluded.base_url,
  enabled=true,
  config=excluded.config;

update public.data_providers set enabled=false where slug='bitbo';

update public.data_series
set provider_id=(select id from public.data_providers where slug='kaporal-etf-primary'),
    provider_series_code='KAPORAL_ESTIMATED_US_SPOT_BTC_ETF_FLOW',
    label='KAPORAL Estimated U.S. Spot Bitcoin ETF Daily Net Flow',
    unit='USD millions',
    frequency='daily',
    source_url='https://www.kaporalintelligence.com/methodology',
    description='KAPORAL-derived estimate based on changes in issuer-published shares outstanding multiplied by the prior business-day NAV. Fund coverage and primary-source provenance are stored with every observation. No paid ETF-flow API is used.',
    metadata=jsonb_build_object(
      'estimated',true,
      'formula','(shares_outstanding_t - shares_outstanding_t_minus_1) * nav_t_minus_1',
      'settlement_alignment','share-count changes observed at T+1 are attributed to the prior business day',
      'validation_only','Farside may be used for manual QA only and is not ingested or republished',
      'cost','free'
    ),
    updated_at=now()
where code='BTC_ETF_FLOW';

insert into public.data_series(code,label,desk_slug,provider_id,provider_series_code,category,region,unit,frequency,source_url,description,is_public,sort_order,metadata)
values
('BTC_ETF_COVERED_AUM','KAPORAL ETF Flow Covered AUM','bitcoin',(select id from public.data_providers where slug='kaporal-etf-primary'),'KAPORAL_ETF_COVERED_AUM','etf_flows','US','USD billions','daily','https://www.kaporalintelligence.com/methodology','Combined assets under management of funds successfully captured by the free KAPORAL ETF Flow Engine on the observation date.',true,98,jsonb_build_object('estimated',false,'cost','free')),
('BTC_ETF_FUNDS_COVERED','KAPORAL ETF Funds Covered','bitcoin',(select id from public.data_providers where slug='kaporal-etf-primary'),'KAPORAL_ETF_FUNDS_COVERED','etf_flows','US','count','daily','https://www.kaporalintelligence.com/methodology','Number of U.S. spot Bitcoin ETF products successfully captured from issuer-published data for the observation date.',true,99,jsonb_build_object('estimated',false,'cost','free'))
on conflict (code) do update set
 label=excluded.label, provider_id=excluded.provider_id, provider_series_code=excluded.provider_series_code, category=excluded.category, region=excluded.region, unit=excluded.unit, frequency=excluded.frequency, source_url=excluded.source_url, description=excluded.description, is_public=excluded.is_public, sort_order=excluded.sort_order, metadata=excluded.metadata, updated_at=now();
