drop policy if exists editor_manage_data_points on public.data_points;
drop policy if exists public_read_data_points on public.data_points;
create policy public_read_data_points_anon on public.data_points for select to anon using (exists (select 1 from public.data_series s where s.id=data_points.series_id and s.is_public=true));
create policy read_data_points_authenticated on public.data_points for select to authenticated using ((exists (select 1 from public.data_series s where s.id=data_points.series_id and s.is_public=true)) or (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text]))));
create policy editor_insert_data_points on public.data_points for insert to authenticated with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_update_data_points on public.data_points for update to authenticated using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text]))) with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_delete_data_points on public.data_points for delete to authenticated using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));

drop policy if exists editor_manage_data_series on public.data_series;
drop policy if exists public_read_data_series on public.data_series;
create policy public_read_data_series_anon on public.data_series for select to anon using (is_public=true);
create policy read_data_series_authenticated on public.data_series for select to authenticated using (is_public=true or exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_insert_data_series on public.data_series for insert to authenticated with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_update_data_series on public.data_series for update to authenticated using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text]))) with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_delete_data_series on public.data_series for delete to authenticated using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));

drop policy if exists editor_manage_impact_maps on public.impact_maps;
drop policy if exists public_read_impact_maps on public.impact_maps;
create policy public_read_impact_maps_anon on public.impact_maps for select to anon using ((article_id is null) or exists (select 1 from public.articles a where a.id=impact_maps.article_id and a.status='published'::article_status and a.published_at<=now()));
create policy read_impact_maps_authenticated on public.impact_maps for select to authenticated using (((article_id is null) or exists (select 1 from public.articles a where a.id=impact_maps.article_id and a.status='published'::article_status and a.published_at<=now())) or exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_insert_impact_maps on public.impact_maps for insert to authenticated with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_update_impact_maps on public.impact_maps for update to authenticated using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text]))) with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_delete_impact_maps on public.impact_maps for delete to authenticated using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));

drop policy if exists editor_manage_impact_nodes on public.impact_nodes;
drop policy if exists public_read_impact_nodes on public.impact_nodes;
create policy public_read_impact_nodes_anon on public.impact_nodes for select to anon using (exists (select 1 from public.impact_maps m where m.id=impact_nodes.impact_map_id and ((m.article_id is null) or exists (select 1 from public.articles a where a.id=m.article_id and a.status='published'::article_status and a.published_at<=now()))));
create policy read_impact_nodes_authenticated on public.impact_nodes for select to authenticated using ((exists (select 1 from public.impact_maps m where m.id=impact_nodes.impact_map_id and ((m.article_id is null) or exists (select 1 from public.articles a where a.id=m.article_id and a.status='published'::article_status and a.published_at<=now())))) or exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_insert_impact_nodes on public.impact_nodes for insert to authenticated with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_update_impact_nodes on public.impact_nodes for update to authenticated using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text]))) with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_delete_impact_nodes on public.impact_nodes for delete to authenticated using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));

drop policy if exists editor_manage_impact_edges on public.impact_edges;
drop policy if exists public_read_impact_edges on public.impact_edges;
create policy public_read_impact_edges_anon on public.impact_edges for select to anon using (exists (select 1 from public.impact_maps m where m.id=impact_edges.impact_map_id and ((m.article_id is null) or exists (select 1 from public.articles a where a.id=m.article_id and a.status='published'::article_status and a.published_at<=now()))));
create policy read_impact_edges_authenticated on public.impact_edges for select to authenticated using ((exists (select 1 from public.impact_maps m where m.id=impact_edges.impact_map_id and ((m.article_id is null) or exists (select 1 from public.articles a where a.id=m.article_id and a.status='published'::article_status and a.published_at<=now())))) or exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_insert_impact_edges on public.impact_edges for insert to authenticated with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_update_impact_edges on public.impact_edges for update to authenticated using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text]))) with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_delete_impact_edges on public.impact_edges for delete to authenticated using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));

drop policy if exists editor_manage_predictions on public.predictions;
drop policy if exists public_read_predictions on public.predictions;
create policy public_read_predictions_anon on public.predictions for select to anon using ((article_id is null) or exists (select 1 from public.articles a where a.id=predictions.article_id and a.status='published'::article_status and a.published_at<=now()));
create policy read_predictions_authenticated on public.predictions for select to authenticated using (((article_id is null) or exists (select 1 from public.articles a where a.id=predictions.article_id and a.status='published'::article_status and a.published_at<=now())) or exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_insert_predictions on public.predictions for insert to authenticated with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_update_predictions on public.predictions for update to authenticated using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text]))) with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_delete_predictions on public.predictions for delete to authenticated using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));

drop policy if exists editor_manage_prediction_resolutions on public.prediction_resolutions;
drop policy if exists public_read_prediction_resolutions on public.prediction_resolutions;
create policy public_read_prediction_resolutions_anon on public.prediction_resolutions for select to anon using (exists (select 1 from public.predictions p where p.id=prediction_resolutions.prediction_id and ((p.article_id is null) or exists (select 1 from public.articles a where a.id=p.article_id and a.status='published'::article_status and a.published_at<=now()))));
create policy read_prediction_resolutions_authenticated on public.prediction_resolutions for select to authenticated using ((exists (select 1 from public.predictions p where p.id=prediction_resolutions.prediction_id and ((p.article_id is null) or exists (select 1 from public.articles a where a.id=p.article_id and a.status='published'::article_status and a.published_at<=now())))) or exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_insert_prediction_resolutions on public.prediction_resolutions for insert to authenticated with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_update_prediction_resolutions on public.prediction_resolutions for update to authenticated using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text]))) with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_delete_prediction_resolutions on public.prediction_resolutions for delete to authenticated using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));

drop policy if exists editor_manage_site_pages on public.site_pages;
drop policy if exists public_read_site_pages on public.site_pages;
create policy public_read_site_pages_anon on public.site_pages for select to anon using ((status='published'::text) and published_at is not null and published_at<=now());
create policy read_site_pages_authenticated on public.site_pages for select to authenticated using (((status='published'::text) and published_at is not null and published_at<=now()) or exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_insert_site_pages on public.site_pages for insert to authenticated with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_update_site_pages on public.site_pages for update to authenticated using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text]))) with check (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
create policy editor_delete_site_pages on public.site_pages for delete to authenticated using (exists (select 1 from public.profiles p where p.id=(select auth.uid()) and p.role=any(array['editor'::text,'admin'::text])));
