import Link from 'next/link'
import { getSignalLab } from '../../../lib/data/signal-lab'
import ForwardEvidence from './ForwardEvidence'
import styles from './signals.module.css'

function pct(value:unknown){if(value==null)return '—';const n=Number(value);return Number.isFinite(n)?`${(n*100).toFixed(1)}%`:'—'}
function number(value:unknown,digits=1){if(value==null)return '—';const n=Number(value);return Number.isFinite(n)?n.toFixed(digits):'—'}

export const metadata={title:'Signal Lab | KAPORAL Research OS',robots:{index:false,follow:false}}
export const dynamic='force-dynamic'

export default async function SignalLabPage({searchParams}:{searchParams:Promise<{model?:string|string[]}>}){
  const query=await searchParams
  const data=await getSignalLab(Array.isArray(query.model)?'invalid-model-selection':query.model)
  if(!data.authorized) return <main className="studio-shell"><section className="studio-lock"><p className="eyebrow">KAPORAL SIGNAL LAB</p><h1>Private quantitative research workspace</h1><p>This surface is restricted to approved researchers, editors and administrators.</p><div className="lockActions"><Link href="/auth">Sign in</Link><Link href="/">Return to public intelligence</Link></div></section></main>

  const model=data.model
  const btc=model?.code==='K-BTC-24H'
  const evaluation=data.backtests.find((b:any)=>b.model_version_id===model?.id)
  const weights=Object.entries((model?.feature_weights??{}) as Record<string,unknown>).sort((a,b)=>Number(b[1])-Number(a[1]))

  return <main className="studio-shell signalLabShell">
    <section className="studio-head"><div><p className="eyebrow">KAPORAL SIGNAL LAB · EXPERIMENTAL</p><h1>{btc?'Bitcoin 24-hour model evidence':model?`${model.code} research evidence`:'Select a model version'}</h1><p>{data.profile.display_name??'Researcher'} · {data.profile.role}</p></div><div className="workspaceActions"><Link href="/studio">Research OS</Link><Link href="/bitcoin">Public Bitcoin desk ↗</Link></div></section>

    <form className={`studio-panel ${styles.versionForm}`} action="/studio/signals" method="get"><label htmlFor="model-version">Model version </label><select id="model-version" name="model" defaultValue={model?.id??''}><option value="" disabled>Select a version</option>{data.models.map(m=><option key={m.id} value={m.id}>{m.code} · {m.version} · {m.status}</option>)}</select> <button className="goldButton" type="submit">View version</button><p>Results never mix versions. Model ID: {model?.id??'none selected'}. Read at {data.asOf}.</p></form>
    {data.errors.length>0&&<section className="signalLabWarning" role="alert"><strong>Data could not be fully verified</strong><ul>{data.errors.map((error,i)=><li key={i}>{error}</li>)}</ul></section>}
    <section className="studio-kpis"><div><small>MODEL</small><b>{model?`${model.code} ${model.version}`:'—'}</b></div><div><small>FORECASTS READ / EXACT COUNT</small><b>{data.forecastCount} / {data.expectedCount??'unknown'}</b></div><div><small>VALID RESOLVED / REVIEW MINIMUM</small><b>{data.forward?`${data.forward.resolved} / ${data.forward.minimum}`:'—'}</b></div><div><small>LEDGER READ</small><b>{data.complete?'Complete':'Incomplete'}</b></div></section>

    <section className="signalLabWarning"><strong>{btc?'Trained baseline · predictive advantage not established':'Private experimental research'}</strong><p>{btc?'The Bitcoin model estimates whether tomorrow’s complete UTC day closes above its open. Its inputs end at 00:00 UTC today; this 24-hour input gap is identical in training and forward use. This is not an immediate now-to-24-hours trade signal. Probabilities remain unvalidated; no price target or opportunity score is estimated.':'Validation requires forward predictions and chronological testing with transaction costs, slippage and no look-ahead.'}</p></section>
    {data.forward&&<ForwardEvidence report={data.forward}/>}
    {btc&&evaluation&&<section className="studio-panel signalTablePanel"><p className="eyebrow">CHRONOLOGICAL TEST · SIMULATED</p><h2>Does the model improve on a simple benchmark?</h2><p>{evaluation.observations} daily targets · {evaluation.period_start} through {evaluation.period_end} (end exclusive). Quarterly fits use only earlier resolved labels. Historical candles are today’s vendor vintage.</p><div className="signalTableScroll"><table className="signalTable"><thead><tr><th>Measure</th><th>Fitted model</th><th>Training up-frequency benchmark</th></tr></thead><tbody><tr><td>Direction accuracy</td><td>{pct((evaluation.evaluation as any)?.hitRate)}</td><td>{pct((evaluation.benchmark as any)?.hitRate)}</td></tr><tr><td>Brier error · lower is better</td><td>{number(evaluation.brier_score,6)}</td><td>{number((evaluation.benchmark as any)?.brier,6)}</td></tr><tr><td>Log loss · lower is better</td><td>{number((evaluation.evaluation as any)?.logLoss,6)}</td><td>{number((evaluation.benchmark as any)?.logLoss,6)}</td></tr></tbody></table></div><p>Brier difference: {number((evaluation.uncertainty as any)?.difference,6)}. Exploratory 95% block-bootstrap interval: {number((evaluation.uncertainty as any)?.lower95,6)} to {number((evaluation.uncertainty as any)?.upper95,6)}. An interval crossing zero does not establish improvement.</p><p>Cost-sensitive returns remain exploratory. The initial threshold produced {number(evaluation.active_days,0)} exposed days, so a positive simulated return or zero daily drawdown does not establish safety or a repeatable edge.</p><p><a href="https://docs.cdp.coinbase.com/api-reference/exchange-api/rest-api/products/get-product-candles" target="_blank" rel="noreferrer">Coinbase source and candle definitions ↗</a></p></section>}

    <section className="signalLabGrid">
      <article className="studio-panel"><p className="eyebrow">MODEL WEIGHTS</p><h2>{btc?'Fitted standardized coefficients':'Current K-EDGE score'}</h2>{btc&&<p>Logistic coefficients describe the fitted association, holding the other features fixed. They are not causal effects or feature importance percentages.</p>}{weights.length?<div className="weightList">{weights.map(([name,value])=><div key={name}><span>{name.replaceAll('_',' ')}</span><b>{number(value,btc?5:0)}</b>{!btc&&<i style={{width:`${Math.max(0,Math.min(100,Number(value)))}%`}}/>}</div>)}</div>:<p>No model weights stored.</p>}</article>
      <article className="studio-panel"><p className="eyebrow">VALIDATION STATUS</p><h2>{model?.status??'No model'}</h2><p>{model?.notes??'No model notes stored.'}</p><dl className="signalMethod"><div><dt>Universe</dt><dd>{btc?'Coinbase BTC-USD only':'Crypto → stocks → listed options'}</dd></div><div><dt>Horizon</dt><dd>{btc?'Next complete UTC day · 24 hours':'24h / 72h / 1 week research windows'}</dd></div><div><dt>Next evidence</dt><dd>{btc?'At least 90 resolved daily forward calls, then calibration, costs and human research review. This minimum does not guarantee sufficient evidence.':'Direction, probability, score, horizon, invalidation'}</dd></div></dl></article>
    </section>

    <section className="studio-panel signalTablePanel"><div className="signalTableHead"><div><p className="eyebrow">FORWARD LEDGER · ROW PREVIEW</p><h2>Predictions made before the outcome</h2></div><span>Latest {data.predictions.length} of {data.forecastCount} fetched for this version; the report above audits every row.</span></div>{data.predictions.length?<div className="signalTableScroll"><table className="signalTable"><thead><tr><th>Inputs / forecast issued (UTC)</th><th>Asset</th><th>Direction</th><th>Target window (UTC)</th><th>Probability · BTC: P(up)</th><th>Opportunity score</th><th>Expected move</th><th>Status</th><th>Invalidation</th></tr></thead><tbody>{data.predictions.map((p:any)=><tr key={p.id}><td>{new Date(p.source_as_of).toLocaleString('en-GB',{timeZone:'UTC',dateStyle:'medium',timeStyle:'short'})}<small>Issued {new Date(p.created_at).toISOString()}</small></td><td><strong>{p.symbol}</strong><small>{p.asset_class}</small></td><td>{p.direction}</td><td>{p.features?.protocol==='btc24-v1'?<>{p.features.window_start}<br/>{p.features.window_end}</>:`${p.horizon_hours}h`}</td><td>{pct(p.probability)}</td><td>{p.features?.protocol==='btc24-v1'?'Unscored':`${number(p.opportunity_score,0)}/100`}</td><td>{p.expected_move_pct==null?'—':`${Number(p.expected_move_pct).toFixed(2)}%`}</td><td>{p.status}</td><td>{p.invalidation_text}</td></tr>)}</tbody></table></div>:<div className="emptyResearch"><strong>{data.complete?'No forward predictions yet.':'Forward ledger unavailable.'}</strong><p>A statistic is shown only after the selected version’s complete ledger has been read and audited.</p></div>}</section>

    <section className="studio-panel signalTablePanel"><div className="signalTableHead"><div><p className="eyebrow">BACKTEST AUDIT</p><h2>Walk-forward evidence</h2></div><span>{data.backtests.length} runs</span></div>{data.backtests.length?<div className="signalTableScroll"><table className="signalTable"><thead><tr><th>Universe</th><th>Period</th><th>Observations</th><th>Hit rate</th><th>Brier</th><th>Avg/day · net</th><th>Daily close drawdown</th></tr></thead><tbody>{data.backtests.map((b:any)=><tr key={b.id}><td>{b.universe}</td><td>{b.period_start} → {b.period_end}</td><td>{b.observations}</td><td>{b.hit_rate==null?'—':`${Number(b.hit_rate).toFixed(1)}%`}</td><td>{number(b.brier_score,3)}</td><td>{b.avg_return_pct==null?'—':`${Number(b.avg_return_pct).toFixed(2)}%`}</td><td>{b.max_drawdown_pct==null?'—':`${Number(b.max_drawdown_pct).toFixed(2)}%`}</td></tr>)}</tbody></table></div>:<div className="emptyResearch"><strong>No backtest has earned a result yet.</strong><p>The database is ready for walk-forward experiments, but a statistic will not be shown until an actual run with documented assumptions is stored.</p></div>}</section>
  </main>
}
